### ISSUE TITLE
explain in more depth about `keep-stage`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#201]
https://github.com/rust-lang-nursery/rustc-guide/pull/191 added some commentary about `--keep-stage 1` but there is probably more to say.

@Mark-Simulacrum [wrote a comment explaining some more workflows](https://github.com/rust-lang-nursery/rustc-guide/pull/191#issuecomment-419601167) but I confess I haven't fully processed it. 

It seems like we should dedicate an entire section (I'd make a new file, perosnally) to keep-stage and explain:

- What exactly it does (e.g., what is the effect of `--keep-stage 0`)
- Common workflows where it can be useful

**Comment by dwijnand** [comment]
I've so many questions for @Mark-Simulacrum about his workflows in https://github.com/rust-lang/rustc-guide/pull/191#issuecomment-419601167:

How does `x.py build --stage 1 --keep-stage 0 src/libstd` "build the compiler once and only once"?  Doesn't it skip compiling the stage 0 compiler and never get to compiling the stage 1 compiler?

Instead of `x.py build --stage 1 src/libstd --keep-stage 1` wouldn't it be faster to do `x.py build --stage 0 src/rustc`?  I think it is but it's missing the uplifting of rustc and sysroot into `build/HOST/stage1`.

Is there a difference between `x.py build --stage 2 --keep-stage 0` and `x.py build --stage 1`?  I think it's not because each stage isn't the same so it's not simply "do two dogfood iterations".

For cross-linking, my general staging discussions are happening in https://github.com/rust-lang/rust/issues/57963.

**Comment by dwijnand** [comment]
Perhaps a good starting point would be off of @nikomatsakis' comment: https://github.com/rust-lang/rustc-guide/pull/191#issuecomment-420327014

What's does `--keep-stage 1` do?

**Comment by mark-i-m** [comment]
Discussed a bit in rust-lang/rust#57963

**Comment by mark-i-m** [comment]
There is more discussion in https://rust-lang.github.io/rustc-guide/building/bootstrapping.html

So I will close this issue, but feel free to reopen...
