### ISSUE TITLE
How does rustc use LLVM ?

### ISSUE THREAD

**Issue by mobop** [rust-lang/rustc-guide#543]
How LLVM is used?

**Comment by JohnTitor** [comment]
Probably you want this: https://rust-lang.github.io/rustc-guide/codegen.html

**Comment by mobop** [comment]
That part of the doc isn't complete yet

**Comment by mark-i-m** [comment]
@mobop Unfortunately, we don't have much on the backend operations of the compiler yet. If you are trying to do something specific you might try hopping over to Zulip and asking there. Otherwise, the code sometimes has helpful comments. One of our goals for the next year is to fill in this gap in the guide...
